name: Build and Push Docker image

on:
  push:
    branches:
      - master  # or your default branch
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/auditorycheesecake:latest

    - name: Logout from DockerHub
      run: docker logout


  deploy:
    needs: build-and-push  # This job runs after build-and-push completes
    runs-on: ubuntu-latest
    steps:
      - name: Installing SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name:
        run: ssh-add -L

      - name: SSH and Deploy Docker Container
        run: |
          # SSH into the server and run Docker commands
          ssh -o StrictHostKeyChecking=no root@134.209.47.131 << 'ENDSSH'
          # Pull the latest version of your image
          docker pull ${{ secrets.DOCKER_USERNAME }}/auditorycheesecake:latest
          
          # Stop the existing container
          docker stop server || true
          docker rm server || true

          # Start a new container
          docker run --name server -d -p 1337:1337 --env-file /root/.env ${{ secrets.DOCKER_USERNAME }}/auditorycheesecake:latest
          ENDSSH

